"""
sec_interpreter/report_formatter.py

Converts validated_output.json + interpretation.json (optional) into a
clean markdown compliance report for a non-technical founder audience.

Entry point: format_report(run_id) -> str
"""
from __future__ import annotations

import json
import os
from datetime import date
from typing import Optional


def format_report(run_id: str) -> str:
    """Load artifacts for run_id and return a markdown report string."""
    artifact_dir = os.path.join("artifacts", run_id)

    validated_path = os.path.join(artifact_dir, "validated_output.json")
    if not os.path.exists(validated_path):
        raise FileNotFoundError(
            f"No validated_output.json for run_id={run_id}. Run extract first."
        )

    with open(validated_path, encoding="utf-8") as f:
        extracted = json.load(f)

    # Interpretation is optional
    interp_path = os.path.join(artifact_dir, "interpretation.json")
    interpretations: dict[str, dict] = {}
    if os.path.exists(interp_path):
        with open(interp_path, encoding="utf-8") as f:
            interp_data = json.load(f)
        for i in interp_data.get("interpretations", []):
            interpretations[i["obligation_id"]] = i

    return _build_report(extracted, interpretations)


# ---------------------------------------------------------------------------
# Internal builders
# ---------------------------------------------------------------------------

def _build_report(extracted: dict, interpretations: dict[str, dict]) -> str:
    parts: list[str] = []

    parts.append(_section_header(extracted))
    parts.append(_section_summary(extracted))
    parts.append(_section_obligations(extracted, interpretations))
    parts.append(_section_impact_areas(extracted))
    parts.append(_section_affected_entities(extracted))

    assumptions = extracted.get("assumptions", [])
    if assumptions:
        parts.append(_section_assumptions(assumptions))

    parts.append(_section_footer())

    return "\n\n".join(parts)


def _section_header(extracted: dict) -> str:
    meta = extracted.get("rule_metadata", {})
    title = meta.get("rule_title", "SEC Regulatory Rule")
    release = meta.get("release_number") or "N/A"
    effective = meta.get("effective_date") or "N/A"
    published = meta.get("publication_date") or "N/A"
    today = date.today().isoformat()

    lines = [
        f"# SEC Compliance Report",
        f"## {title}",
        "",
        f"| Field           | Value         |",
        f"|-----------------|---------------|",
        f"| Release Number  | {release}     |",
        f"| Published       | {published}   |",
        f"| Effective Date  | {effective}   |",
        f"| Report Date     | {today}       |",
        "",
        "> **Advisory note:** This report is generated by an AI tool and is intended to",
        "> support compliance planning discussions. It is not legal advice. Consult qualified",
        "> legal counsel before making compliance decisions.",
    ]
    return "\n".join(lines)


def _section_summary(extracted: dict) -> str:
    summary_text = extracted.get("rule_summary", {}).get("summary", "")
    lines = [
        "---",
        "## Rule Summary",
        "",
        summary_text,
    ]
    return "\n".join(lines)


def _section_obligations(extracted: dict, interpretations: dict[str, dict]) -> str:
    obligations = extracted.get("key_obligations", [])
    total = len(obligations)

    lines = [
        "---",
        f"## Obligations  ({total} total)",
    ]

    for obl in obligations:
        lines.append("")
        lines.append(_format_obligation(obl, interpretations.get(obl["obligation_id"])))

    return "\n".join(lines)


def _format_obligation(obl: dict, interp: Optional[dict]) -> str:
    obl_id = obl.get("obligation_id", "OBL-???")
    obl_text = obl.get("obligation_text", "")

    lines = [
        f"### {obl_id} -- {obl_text}",
        "",
    ]

    # Core fields
    trigger = obl.get("trigger")
    deadline = obl.get("deadline")
    cited = obl.get("cited_sections", [])

    if trigger or deadline or cited:
        if trigger:
            lines.append(f"**Trigger:** {trigger}  ")
        if deadline:
            lines.append(f"**Deadline:** {deadline}  ")
        if cited:
            lines.append(f"**CFR / Form reference:** {', '.join(cited)}  ")
        lines.append("")

    # What to disclose
    disclosure_fields = obl.get("disclosure_fields", [])
    if disclosure_fields:
        lines.append("**What to disclose:**")
        for item in disclosure_fields:
            lines.append(f"  - {item}")
        lines.append("")

    # Evidence
    evidence = obl.get("evidence", [])
    if evidence:
        lines.append("**Evidence needed:**")
        for item in evidence:
            lines.append(f"  - {item}")
        lines.append("")

    # Interpretation block
    if interp:
        lines.append(_format_interpretation(interp))

    lines.append("---")
    return "\n".join(lines)


def _format_interpretation(interp: dict) -> str:
    primary = interp.get("primary_interpretation", "")
    implication = interp.get("compliance_implication", "")
    ambiguous = interp.get("ambiguous_terms", [])
    alternatives = interp.get("alternative_interpretations", [])
    confidence = interp.get("confidence_level", "medium").upper()
    supporting = interp.get("supporting_sections", [])

    lines = ["#### Interpretation"]
    lines.append("")
    lines.append(primary)
    lines.append("")

    if implication:
        lines.append(f"**Compliance action:** {implication}")
        lines.append("")

    if ambiguous:
        lines.append(f"**Ambiguous terms:** {', '.join(ambiguous)}")
        lines.append("")

    if supporting:
        lines.append(f"**Sources used:** {', '.join(supporting)}")
        lines.append("")

    if alternatives:
        lines.append("**Alternative readings:**")
        for alt in alternatives:
            lines.append(f"  > {alt}")
        lines.append("")

    lines.append(f"*Confidence: {confidence}*")
    lines.append("")

    return "\n".join(lines)


def _section_impact_areas(extracted: dict) -> str:
    areas = extracted.get("compliance_impact_areas", [])
    if not areas:
        return ""

    lines = [
        "---",
        "## Compliance Impact Areas",
        "",
        "| Area | Linked Obligations |",
        "|------|--------------------|",
    ]
    for area in areas:
        name = area.get("area", "")
        ids = ", ".join(area.get("linked_obligation_ids", []))
        lines.append(f"| {name} | {ids} |")

    return "\n".join(lines)


def _section_affected_entities(extracted: dict) -> str:
    entities = extracted.get("affected_entity_types", [])
    if not entities:
        return ""

    lines = [
        "---",
        "## Affected Entity Types",
        "",
    ]
    for ent in entities:
        lines.append(f"- {ent.get('entity_type', '')}")

    return "\n".join(lines)


def _section_assumptions(assumptions: list) -> str:
    lines = [
        "---",
        "## Assumptions and Limitations",
        "",
    ]
    for i, a in enumerate(assumptions, 1):
        text = a.get("assumption_text", "")
        reason = a.get("reason", "")
        lines.append(f"{i}. **{text}**")
        if reason:
            lines.append(f"   *Reason: {reason}*")
        lines.append("")

    return "\n".join(lines)


def _section_footer() -> str:
    lines = [
        "---",
        "*Generated by SEC Rule Compliance Extractor. "
        "This output is advisory only and does not constitute legal advice.*",
    ]
    return "\n".join(lines)
